{% set name = "python-xxhash" %}
{% set version = "4.0.1" %}
{% set pip_name = "xxhash" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz
  sha256: d55bf4ef10eb09b8b6866790e083d26d087d84caa3cc0946ba87c3ca7ecaf7b7

build:
  number: 0
  script:
    - export XXHASH_LINK_SO=1  # [unix]
    - SET XXHASH_LINK_SO=1  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=45
    - xxhash {{ xxhash }}
  run:
    - python
    - xxhash

test:
  imports:
    - xxhash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ifduyue/python-xxhash
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Python binding for xxHash
  description: |
    Python binding for xxHash which is an extremely fast hash algorithm, processing at RAM speed limits. Code is highly portable, and produces hashes identical across all platforms (little / big endian).
  license_family: BSD
  doc_url: https://github.com/ifduyue/python-xxhash
  dev_url: https://github.com/ifduyue/python-xxhash

extra:
  recipe-maintainers:
    - mariusvniekerk
