{% set version = "3.5.0" %}
{% set sha256 = "84f2caddf951c9cbf8dc2e22a89d4ccf5d86391ac6418fe81e3c67d0cf60b45f" %}
{% set pip_name = "xxhash" %}
{% set name = "python-xxhash" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: {{ sha256 }}
  url: https://pypi.io/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz

build:
  number: 0
  script:
    - export XXHASH_LINK_SO=1  # [unix]
    - SET XXHASH_LINK_SO=1  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - msinttypes  # [win and py<35]
    - pip
    - setuptools
    - wheel
    - xxhash
  run:
    - python
    - xxhash

test:
  imports:
    - xxhash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ifduyue/python-xxhash
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Python binding for xxHash
  description: |
    Python binding for xxHash which is an extremely fast hash algorithm, processing at RAM speed limits. Code is highly portable, and produces hashes identical across all platforms (little / big endian).
  license_family: BSD
  doc_url: https://github.com/ifduyue/python-xxhash
  dev_url: https://github.com/ifduyue/python-xxhash

extra:
  recipe-maintainers:
    - mariusvniekerk
