travis:
  secure:
    BINSTAR_TOKEN: mNcYX1Sn0BO6UkqpTYe3eQzXbGq0ahuMI8wpavqxJGPZrTZWFhUylCRmBM4uHQV7dxMJ6VnkJUjdxAY8D878gLBbGT6oY71JimSKbyQyiHPNSCb9gzRIi1gTLKAoNL3iKjBWN4BpRmRs7LoB7Uu4UQz4ER4hqPFUQ92AiEZMjE23OL1pzrUarkFwiBSVQiTPDpSE06+/53hq3zYeDKnLsotBjwH+sIekvl0yiKbytVUgH7cAKaWqO+ZJEqmLPoFJ/yI6rnuqMcmW0VN4w/ScmWOxhuoE6+JzfgB8Bryej6/PVmGAQiPeir4813NzoWJtJXrBFRylaqzB+x+Vc1pJObn0YEwp/TKNTjaZ7m1lwjra2RDhAOwjaB87UfPcVDT834kN4Nv8kEbrmGkxc6P2gc450W4c8rgI+rnewIxkljqI+OrPHw5zii8xys+O4ND1e8I4/ZQcVjpaMAnGLoKQibksO4q6zY1S0dTkn/3wy+47PXasZKUsbtRb9CaDpXqS+wtHo5UnKcS0ICoO4VmDpNB747dch9mO4air1Su4OfyqYbqkVpTKRUxAstKUvzn4BkCnKqkJ3GKOjR122s8cFHYIhP90AYx4XaPLZ+YQ9M/who15Tz9TmexQ3xtbMcpVO1u3mT9fZbiJ8JOCCri41X29OXgYWNjnIsDaXmCyxMQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
